/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Tabla;
import dao.imp.ImpiProducto_DAO;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.Producto;

/**
 *
 * @author fetox
 */
public class Agregar extends javax.swing.JInternalFrame {

    Tabla t = new Tabla();
    Producto pr = new Producto();
    ImpiProducto_DAO iipd = new ImpiProducto_DAO();
    /**
     * Creates new form NewJInternalFrame
     */
    int Fi = 0;

    public Agregar() throws IOException {
        initComponents();
        jTable1.setModel(t.inventario());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton2.setText("Ingresar Unidades");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione un producto para agregar unidades");

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jButton2)
                .addGap(118, 118, 118)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int Fi = jTable1.getSelectedRow();

        if (Fi < 0) {

            String Mensaje = "Elija Un Producto Antes de Continuar";
            JOptionPane.showMessageDialog(null, Mensaje, "", JOptionPane.ERROR_MESSAGE);

        } else {

            String id = String.valueOf(jTable1.getValueAt(Fi, 0));
            String Producto = String.valueOf(jTable1.getValueAt(Fi, 1));
            String descripcion = String.valueOf(jTable1.getValueAt(Fi, 2));
            String compra = String.valueOf(jTable1.getValueAt(Fi, 3));
            String venta = String.valueOf(jTable1.getValueAt(Fi, 4));
            String fechav = String.valueOf(jTable1.getValueAt(Fi, 5));
            String cantidad = String.valueOf(jTable1.getValueAt(Fi, 6));

            int n = Integer.parseInt(id);
            try {
                pr = iipd.findByID(n);
            } catch (IOException ex) {
                Logger.getLogger(Agregar.class.getName()).log(Level.SEVERE, null, ex);
            }

            int i = pr.getId();
            String prod = pr.getNproducto();
            String desc = pr.getDescripcion();
            String cc = pr.getCcompra();
            String cv = pr.getCventa();
            String fv = pr.getFechav();
            String cant = pr.getCanditad();

            String Mensaje = "       Producto Seleccionado\n" + "Id: " + id + "\n" + "Producto: " + prod + "\n" + "Descripcion: " + desc + "\n" + "Costo: " + cc + "\n"
                    + "Venta :" + cv + "\n" + "Fecha de vencimiento: " + fv + "\n" + "Cantidad :" + cant;
            String cantd = JOptionPane.showInputDialog(null, Mensaje, "Pulperia", JOptionPane.INFORMATION_MESSAGE);
            if (!(cantd == null || cantd == "")) {

                int x = Integer.parseInt(cant);
                int y = Integer.parseInt(cantd);

                int can = x + y;
                String ncant = String.valueOf(can);

                pr.setId(i);
                pr.setNproducto(prod);
                pr.setDescripcion(desc);
                pr.setCcompra(cc);
                pr.setCventa(cv);
                pr.setFechav(fv);
                pr.setCanditad(ncant);

                try {
                    iipd.update(pr);

                } catch (IOException ex) {

                }

                Mensaje = "Se han ingresado las nuevas unidades del Producto Seleccionado";
                JOptionPane.showMessageDialog(null, Mensaje, "", JOptionPane.INFORMATION_MESSAGE);

                try {
                    setClosed(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(NuevoP.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
            JOptionPane.showMessageDialog(null, "Ingrese una cantidad", "Pulperia", JOptionPane.INFORMATION_MESSAGE);
            }
        
         
         }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(NuevoP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
